name: Build and Publish Hangfire Recurring Job Manager NuGet Package

on:
  pull_request:
    branches: 
      - master
      - develop    
  push:
    branches: 
      - master
      - develop

jobs:
  build:
    strategy:
      matrix:
        os: 
          - macOS-latest
          - ubuntu-latest
          - windows-latest

    runs-on: ${{matrix.os}}
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.2.108

      - name: Install dependencies on Ubuntu
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl1.1

      - name: Build with dotnet
        run: dotnet build --configuration Release src/Be.Auto.Hangfire.Dashboard.RecurringJobManager/Be.Auto.Hangfire.Dashboard.RecurringJobManager.csproj

      - name: Pack NuGet Package
        run: dotnet pack --configuration Release --output ./nupkg src/Be.Auto.Hangfire.Dashboard.RecurringJobManager/Be.Auto.Hangfire.Dashboard.RecurringJobManager.csproj

      - name: Publish to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push ./nupkg/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
