name: Build and Publish Hangfire Recurring Job Manager NuGet Package

on:
  push:
    branches:
      - main
      - 'releases/*'
    paths:
      - 'src/Be.Auto.Hangfire.Dashboard.RecurringJobManager/**'
  pull_request:
    branches:
      - main
    paths:
      - 'src/Be.Auto.Hangfire.Dashboard.RecurringJobManager/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.0.x' # .NET Standard 2.0 için gerekli

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl1.1
        msbuild /t:Restore src/Be.Auto.Hangfire.Dashboard.RecurringJobManager/Be.Auto.Hangfire.Dashboard.RecurringJobManager.csproj

    - name: Build
      run: msbuild /p:Configuration=Release src/Be.Auto.Hangfire.Dashboard.RecurringJobManager/Be.Auto.Hangfire.Dashboard.RecurringJobManager.csproj

    - name: Pack
      run: msbuild /t:Pack /p:Configuration=Release src/Be.Auto.Hangfire.Dashboard.RecurringJobManager/Be.Auto.Hangfire.Dashboard.RecurringJobManager.csproj /p:PackageOutputPath=./nupkg

    - name: Publish to NuGet
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push ./nupkg/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
